{
 "title": "Printers Monitor",
 "description": "General information for any network printer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ip",
    "label": "IP Printer",
    "query": "SHOW TAG VALUES FROM \"printer\" WITH KEY = \"agent_host\""
   }
  ]
 },
 "panels": [
  { "title": "$ip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ip" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "printer",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Cover Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "prtCoverDescription" ], "type": "tag" }
     ],
     "measurement": "printer",
     "select": [
      [
       { "params": [ "prtCoverStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Supplies",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "prtMarkerSuppliesDescription" ], "type": "tag" }
     ],
     "measurement": "printer",
     "query": "SELECT last(\"prtMarkerSuppliesLevel\") AS \"level\", last(\"prtMarkerSuppliesMaxCapacity\") AS \"capacity\", mean(\"prtMarkerSuppliesLevel\") *100 / mean(\"prtMarkerSuppliesMaxCapacity\") AS \"remaining\" FROM \"printer\" WHERE (\"agent_host\" =~ /^$ip$/) AND $timeFilter GROUP BY \"prtMarkerSuppliesDescription\"",
     "select": [
      [
       { "params": [ "prtMarkerSuppliesLevel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "level" ], "type": "alias" }
      ],
      [
       { "params": [ "prtMarkerSuppliesMaxCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "capacity" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Impressions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "printer",
     "select": [
      [
       { "params": [ "prtMarkerLifeCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Printer Uptime",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "$tag_agent_host ($tag_hrDeviceDescr)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "hrDeviceDescr" ], "type": "tag" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "printer",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Printer Cover Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "$tag_agent_host ($tag_prtCoverDescription)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "prtCoverDescription" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "printer",
     "select": [
      [
       { "params": [ "prtCoverStatus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Printed pages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host ($tag_hrDeviceDescr)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "hrDeviceDescr" ], "type": "tag" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "printer",
     "select": [
      [
       { "params": [ "prtMarkerLifeCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Supplies Remaining",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host ($tag_prtMarkerSuppliesDescription)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "prtMarkerSuppliesDescription" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "printer",
     "query": "SELECT mean(\"prtMarkerSuppliesLevel\") *100 / mean(\"prtMarkerSuppliesMaxCapacity\") FROM \"printer\" WHERE (\"agent_host\" =~ /^$ip$/) AND $timeFilter GROUP BY time(5m), \"agent_host\", \"prtMarkerSuppliesDescription\" fill(none)",
     "select": [
      [
       { "params": [ "prtMarkerSuppliesLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Level" ], "type": "alias" }
      ],
      [
       { "params": [ "prtMarkerSuppliesMaxCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Capacity" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  }
 ]
}